In [6]:
import pandas as pd

BASE = "produtos_regioes.csv"
df = pd.read_csv(BASE)
df

   produto        regiao  receita
0        A         Norte      100
1        B           Sul      150
2        C      Nordeste      200
3        A  Centro-Oeste      120
4        B       Sudeste      160
5        C           Sul      210
6        A  Centro-Oeste      130
7        B         Norte      170
8        C      Nordeste      220
9        A           Sul      140
10       A       Sudeste      110
11       B         Norte      155
12       C  Centro-Oeste      215
13       B           Sul      165
14       C         Norte      225
15       A       Sudeste      180
16       B      Nordeste      175
17       C           Sul      190
18       A  Centro-Oeste      160
19       B       Sudeste      155

In [7]:
pd.crosstab(df["regiao"], df["produto"])

produto       A  B  C
regiao
Centro-Oeste  3  0  1
Nordeste      0  1  2
Norte         1  2  1
Sudeste       2  2  0
Sul           1  2  2

In [12]:
pd.crosstab(df['regiao'], df['produto'], margins=True,margins_name='Vendas')

produto       A  B  C  Vendas
regiao
Centro-Oeste  3  0  1       4
Nordeste      0  1  2       3
Norte         1  2  1       4
Sudeste       2  2  0       4
Sul           1  2  2       5
Vendas        7  7  6      20

In [15]:
pd.crosstab(df['regiao'], df['produto'],normalize=True, margins=True, margins_name='Total')

produto          A     B     C  Total
regiao
Centro-Oeste  0.15  0.00  0.05   0.20
Nordeste      0.00  0.05  0.10   0.15
Norte         0.05  0.10  0.05   0.20
Sudeste       0.10  0.10  0.00   0.20
Sul           0.05  0.10  0.10   0.25
Total         0.35  0.35  0.30   1.00

In [16]:
pd.crosstab(
    df['regiao'], df['produto'],normalize=True, margins=True, margins_name='Total'
    ).mul(100)

produto          A     B     C  Total
regiao
Centro-Oeste  15.0   0.0   5.0   20.0
Nordeste       0.0   5.0  10.0   15.0
Norte          5.0  10.0   5.0   20.0
Sudeste       10.0  10.0   0.0   20.0
Sul            5.0  10.0  10.0   25.0
Total         35.0  35.0  30.0  100.0

In [17]:
pd.crosstab(df['regiao'], df['produto'], 
            margins=True,margins_name='Vendas')

produto       A  B  C  Vendas
regiao
Centro-Oeste  3  0  1       4
Nordeste      0  1  2       3
Norte         1  2  1       4
Sudeste       2  2  0       4
Sul           1  2  2       5
Vendas        7  7  6      20

In [19]:
pd.crosstab(df['regiao'], df['produto'],normalize="index", 
            margins=True,margins_name='Total').mul(100).round(1)

produto          A     B     C
regiao
Centro-Oeste  75.0   0.0  25.0
Nordeste       0.0  33.3  66.7
Norte         25.0  50.0  25.0
Sudeste       50.0  50.0   0.0
Sul           20.0  40.0  40.0
Total         35.0  35.0  30.0

In [20]:
pd.crosstab(
    df['regiao'], df['produto'],normalize="columns", 
            margins=True,margins_name='Total').mul(100).round(1)

produto          A     B     C  Total
regiao
Centro-Oeste  42.9   0.0  16.7   20.0
Nordeste       0.0  14.3  33.3   15.0
Norte         14.3  28.6  16.7   20.0
Sudeste       28.6  28.6   0.0   20.0
Sul           14.3  28.6  33.3   25.0

In [24]:
pd.crosstab(df['regiao'], df['produto'])

produto       A  B  C
regiao
Centro-Oeste  3  0  1
Nordeste      0  1  2
Norte         1  2  1
Sudeste       2  2  0
Sul           1  2  2

In [26]:
pd.crosstab(df['regiao'], df['produto'], values=df['receita'], 
            aggfunc='sum', margins=True, margins_name='Receita Total').round(2)

produto            A       B       C  Receita Total
regiao
Centro-Oeste   410.0     NaN   215.0            625
Nordeste         NaN   175.0   420.0            595
Norte          100.0   325.0   225.0            650
Sudeste        290.0   315.0     NaN            605
Sul            140.0   315.0   400.0            855
Receita Total  940.0  1130.0  1260.0           3330

In [29]:
pd.crosstab(df['regiao'], df['produto'], values=df['receita'], 
            aggfunc='sum', normalize=True).mul(100).round(2)

produto           A     B      C
regiao
Centro-Oeste  12.31  0.00   6.46
Nordeste       0.00  5.26  12.61
Norte          3.00  9.76   6.76
Sudeste        8.71  9.46   0.00
Sul            4.20  9.46  12.01

In [30]:
pd.crosstab(df['regiao'], df['produto'], values=df['receita'], 
            aggfunc='sum', normalize="index").mul(100).round(2)

produto           A      B      C
regiao
Centro-Oeste  65.60   0.00  34.40
Nordeste       0.00  29.41  70.59
Norte         15.38  50.00  34.62
Sudeste       47.93  52.07   0.00
Sul           16.37  36.84  46.78

In [31]:
pd.crosstab(df['regiao'], df['produto'], values=df['receita'], 
            aggfunc='sum', normalize='columns').mul(100).round(2)

produto           A      B      C
regiao
Centro-Oeste  43.62   0.00  17.06
Nordeste       0.00  15.49  33.33
Norte         10.64  28.76  17.86
Sudeste       30.85  27.88   0.00
Sul           14.89  27.88  31.75

In [32]:
pd.crosstab(df['regiao'], df['produto'])

produto       A  B  C
regiao
Centro-Oeste  3  0  1
Nordeste      0  1  2
Norte         1  2  1
Sudeste       2  2  0
Sul           1  2  2

In [37]:
df.groupby(['regiao', 'produto']).count().unstack().fillna(0).rename(columns={'receita':'vendas'})

             vendas
produto           A    B    C
regiao
Centro-Oeste    3.0  0.0  1.0
Nordeste        0.0  1.0  2.0
Norte           1.0  2.0  1.0
Sudeste         2.0  2.0  0.0
Sul             1.0  2.0  2.0